#!/bin/bash

### BEGIN INIT INFO
# Provides:        earl
# Required-Start:  $network $remote_fs $syslog $time
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start NTP daemon
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/local/bin/earl
PIDFILE=/var/run/earl.pid
LOGFILE=/var/log/earl
SERIAL_INTERFACES="/dev/ttyUSB0 /dev/ttyUSB1 /dev/ttyAMA0"
test -x $DAEMON || exit 5

RUNASUSER=pi

case $1 in 
	start)
		log_daemon_msg "Starting earl" "earl"
		touch $PIDFILE $LOGFILE
		chown $RUNASUSER:root $PIDFILE $LOGFILE
		start-stop-daemon \
			--start --oknodo \
			--background \
			--make-pidfile \
                        --chuid $RUNASUSER \
			--pidfile $PIDFILE \
			--startas $DAEMON \
			-- -logfile=$LOGFILE \
		        $SERIAL_INTERFACES
		status=$?
		log_end_msg $status
		;;
	stop)
		log_daemon_msg "Stopping earl" "earl"
		start-stop-daemon \
			--stop \
			--oknodo \
			--pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
		;;
	restart)
		$0 stop && sleep 2 && $0 start
		;;
	status)
		status_of_proc $DAEMON "earl"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 2
		;;
esac



